<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use GuzzleHttp;
use App\Http\Controllers\Controller;
use Pdf;
use Illuminate\Support\Facades\Http;

class PDFController extends Controller
{
    //
    public function call(Request $request)
    {
        return view('test');
        //dd($request);
    }
    public function index()
    {
        $client = new GuzzleHttp\Client();
        /* $res = $client->request('GET', 'https://reqres.in/api/users?page=1', [
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                //'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUXlNemM0TVRVc0ltNWlaaUk2TVRjeU5ESXpOemd4TlN3aVpYaHdJam94TnpJME1qUXhOekUxTENKaGFXOGlPaUpCVTFGQk1pODRXRUZCUVVGeVRFZFBTa3BaT0hSc0syTnVNVWxsUlV4SmVXeDJXWG92YlhoMUwweEJWR3B6YlRoaE4wMUZXbVpSUFNJc0ltRjZjQ0k2SW1NMllUZzRNbVV4TFRneVl6Y3RORFUwWkMwNU1EVTVMVGRpTVdFNFlqWmpZVEV4TVNJc0ltRjZjR0ZqY2lJNklqRWlMQ0p2YVdRaU9pSmpPR1ZpT0dOaU9DMHlOems0TFRRek9UY3RPREF3WWkwNFpUUTNOalJsTXpKaU1HWWlMQ0p5YUNJNklqQXVRVkV3UVRGc1gwZFVTR0ZqWTFWcGJGRjFjMU53WVdWQlJFZExPRVpVVVV3dFpIUkxhWFJDZGtoc1dsYzRka0ZPUVVGQkxpSXNJbkp2YkdWeklqcGJJa0ZRU1VGalkyVnpjeUpkTENKemRXSWlPaUpqT0dWaU9HTmlPQzB5TnprNExUUXpPVGN0T0RBd1lpMDRaVFEzTmpSbE16SmlNR1lpTENKMGFXUWlPaUkwWTJNMk5XWmtOaTA1WXpjMkxUUTROekV0WVRVME1pMWxZakV5WVRWaE56Z3dNR01pTENKMWRHa2lPaUp2U2twaE0wdG1SVVF3VDNOQ1YxWnpjbGhZVkVGQklpd2lkbVZ5SWpvaU1pNHdJaXdpWVhCd1JHRjBZU0k2SW50Y0luVnBaRndpT2pFMU56TTBPU3hjSW1GcFpGd2lPakl3TVRBMU1UUjlJbjAuZW92b2N2VHEyYmoxLU01OUVTV280ekNjeS1qR04tRmsxZXhQdl9LbkVfTkF0Tm5VeFVQOElaR3RVX2wxVmlvd0MxNzB0dGNzX2F1NXBORU5BSExsdE1xNEgtblJqeUxVM0lNcVFtNGcyb205aVlOOEhvaUs2endqcThzaVZvZDBlQ0gxZ3RnVU5wRFNjUkliN28wMEY0NnlvYXphRkVhcmpLOHdLbXVlZVVzU0ZnT25ORDNrYzJqN01KM2F2bzdhQm1pMUZoVzVSSFJOenpxaHdWWWcwQzlNNEkyVm1tNTNabF9OZGJsSTBkdXNvNHNCSDhleGYwUzY4Tml4bWZlbzZ4NDVxZGJzbDRiSC1WTmx2M083OWdsNFZzT1dXS0laWmtDb1dVM2VXVEtqTXpEVllhbFRaZ194YmhpRHJuOHlWTW13WDNQUjctbk84YUtZRzNCVGRRIiwiQXZhaWxhYmxlUHJvZHVjdHMiOiJbXCIxMDA4XCIsXCIxMDUzXCIsXCIxMDA1XCIsXCIxMDExXCIsXCIyMDg5XCIsXCIxMDI2XCIsXCIxMDI3XCIsXCIxMDI4XCIsXCI1MDAwXCIsXCI1MDAxXCIsXCI1MDAzXCIsXCIyMDAwXCIsXCIyMDAxXCIsXCIyMDAyXCIsXCIyMDAzXCIsXCIyMDA0XCIsXCIyMDA1XCJdIiwibmJmIjoxNzI0MjM4MTE1LCJleHAiOjE3MjQyNDUzMTUsImlhdCI6MTcyNDIzODExNSwiaXNzIjoiaHR0cHM6Ly9kdGFwaXVhdC5kYXRhdHJlZS5jb20iLCJhdWQiOiJXZWJBcGlDb25zdW1lcnMifQ.RHdGdZAmxTpQ5Jlv51TwWwLwMOk2-UXm30w8yRHER5A'

            ]
        ]);*/

        /*$res = $client->request('POST', 'https://dtapiuat.datatree.com:443/api/Login/AuthenticateClient', [
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                //'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUXlNemM0TVRVc0ltNWlaaUk2TVRjeU5ESXpOemd4TlN3aVpYaHdJam94TnpJME1qUXhOekUxTENKaGFXOGlPaUpCVTFGQk1pODRXRUZCUVVGeVRFZFBTa3BaT0hSc0syTnVNVWxsUlV4SmVXeDJXWG92YlhoMUwweEJWR3B6YlRoaE4wMUZXbVpSUFNJc0ltRjZjQ0k2SW1NMllUZzRNbVV4TFRneVl6Y3RORFUwWkMwNU1EVTVMVGRpTVdFNFlqWmpZVEV4TVNJc0ltRjZjR0ZqY2lJNklqRWlMQ0p2YVdRaU9pSmpPR1ZpT0dOaU9DMHlOems0TFRRek9UY3RPREF3WWkwNFpUUTNOalJsTXpKaU1HWWlMQ0p5YUNJNklqQXVRVkV3UVRGc1gwZFVTR0ZqWTFWcGJGRjFjMU53WVdWQlJFZExPRVpVVVV3dFpIUkxhWFJDZGtoc1dsYzRka0ZPUVVGQkxpSXNJbkp2YkdWeklqcGJJa0ZRU1VGalkyVnpjeUpkTENKemRXSWlPaUpqT0dWaU9HTmlPQzB5TnprNExUUXpPVGN0T0RBd1lpMDRaVFEzTmpSbE16SmlNR1lpTENKMGFXUWlPaUkwWTJNMk5XWmtOaTA1WXpjMkxUUTROekV0WVRVME1pMWxZakV5WVRWaE56Z3dNR01pTENKMWRHa2lPaUp2U2twaE0wdG1SVVF3VDNOQ1YxWnpjbGhZVkVGQklpd2lkbVZ5SWpvaU1pNHdJaXdpWVhCd1JHRjBZU0k2SW50Y0luVnBaRndpT2pFMU56TTBPU3hjSW1GcFpGd2lPakl3TVRBMU1UUjlJbjAuZW92b2N2VHEyYmoxLU01OUVTV280ekNjeS1qR04tRmsxZXhQdl9LbkVfTkF0Tm5VeFVQOElaR3RVX2wxVmlvd0MxNzB0dGNzX2F1NXBORU5BSExsdE1xNEgtblJqeUxVM0lNcVFtNGcyb205aVlOOEhvaUs2endqcThzaVZvZDBlQ0gxZ3RnVU5wRFNjUkliN28wMEY0NnlvYXphRkVhcmpLOHdLbXVlZVVzU0ZnT25ORDNrYzJqN01KM2F2bzdhQm1pMUZoVzVSSFJOenpxaHdWWWcwQzlNNEkyVm1tNTNabF9OZGJsSTBkdXNvNHNCSDhleGYwUzY4Tml4bWZlbzZ4NDVxZGJzbDRiSC1WTmx2M083OWdsNFZzT1dXS0laWmtDb1dVM2VXVEtqTXpEVllhbFRaZ194YmhpRHJuOHlWTW13WDNQUjctbk84YUtZRzNCVGRRIiwiQXZhaWxhYmxlUHJvZHVjdHMiOiJbXCIxMDA4XCIsXCIxMDUzXCIsXCIxMDA1XCIsXCIxMDExXCIsXCIyMDg5XCIsXCIxMDI2XCIsXCIxMDI3XCIsXCIxMDI4XCIsXCI1MDAwXCIsXCI1MDAxXCIsXCI1MDAzXCIsXCIyMDAwXCIsXCIyMDAxXCIsXCIyMDAyXCIsXCIyMDAzXCIsXCIyMDA0XCIsXCIyMDA1XCJdIiwibmJmIjoxNzI0MjM4MTE1LCJleHAiOjE3MjQyNDUzMTUsImlhdCI6MTcyNDIzODExNSwiaXNzIjoiaHR0cHM6Ly9kdGFwaXVhdC5kYXRhdHJlZS5jb20iLCJhdWQiOiJXZWJBcGlDb25zdW1lcnMifQ.RHdGdZAmxTpQ5Jlv51TwWwLwMOk2-UXm30w8yRHER5A'

            ],
            'body' => json_encode([
                'ClientId' => 'c6a882e1-82c7-454d-9059-7b1a8b6ca111',
                'ClientSecretKey' => 'e.s8Q~1R60mIoazbIJFHeeuLKbRs_zu_JeuHJcui'
            ])
        ]);*/
        /*$res = $client->request('POST', 'https://dtapiuat.datatree.com/api/Report/GetReport', [
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUTROall4Tmprc0ltNWlaaUk2TVRjeU5EZzJOakUyT1N3aVpYaHdJam94TnpJME9EY3dNRFk1TENKaGFXOGlPaUpCVTFGQk1pODRXRUZCUVVGTFFuQmhhVzVVWjFWeWFHbGhOa05xZDA1ck56RTJWRFkwVkVwR1EyRmhSR2M1U0dkaGIwczVNemc0UFNJc0ltRjZjQ0k2SW1NMllUZzRNbVV4TFRneVl6Y3RORFUwWkMwNU1EVTVMVGRpTVdFNFlqWmpZVEV4TVNJc0ltRjZjR0ZqY2lJNklqRWlMQ0p2YVdRaU9pSmpPR1ZpT0dOaU9DMHlOems0TFRRek9UY3RPREF3WWkwNFpUUTNOalJsTXpKaU1HWWlMQ0p5YUNJNklqQXVRVkV3UVRGc1gwZFVTR0ZqWTFWcGJGRjFjMU53WVdWQlJFZExPRVpVVVV3dFpIUkxhWFJDZGtoc1dsYzRka0ZPUVVGQkxpSXNJbkp2YkdWeklqcGJJa0ZRU1VGalkyVnpjeUpkTENKemRXSWlPaUpqT0dWaU9HTmlPQzB5TnprNExUUXpPVGN0T0RBd1lpMDRaVFEzTmpSbE16SmlNR1lpTENKMGFXUWlPaUkwWTJNMk5XWmtOaTA1WXpjMkxUUTROekV0WVRVME1pMWxZakV5WVRWaE56Z3dNR01pTENKMWRHa2lPaUp4Vm1Wb2JWTlZkVE5yWlVvNFZuZzNRMnB2YWtGQklpd2lkbVZ5SWpvaU1pNHdJaXdpWVhCd1JHRjBZU0k2SW50Y0luVnBaRndpT2pFMU56TTBPU3hjSW1GcFpGd2lPakl3TVRBMU1UUjlJbjAuRlp6UzdqWWljeWt6bHdEelRIVVBCRGg1WG5mNzZCT09Kblp3eE1zTV9nZGZtS1NvOEc0QzJmZElaS21zZ3lCOURLOEF2SDF2OU4yM0JRakJWRGdtVmk0ZkhxOUFrYUZDTEtkU1l6aDJOTE90N3YwajVta0ZCTFg0TXFvSVVvVWFzanc2ZERXTDV6TUtMekhXY2pfbVh0Z0hQN2t5anhUTWxUeDQ1OEVsdmV4WVVOdzliYzZpd1FPZ2ZVcXBaMndxcHVKNllldU9ON0Nsam1oVUJkZmNwem5FaGVudl9NXzNBZFpjUkpfeHhMektwaGIyLUNmMzJlSEE4VmtWZFVpUHpqMTFxZXVvVnBDeWxWUzkwWmFCU3FqNzVqZWRZb2RxN1QzaERvYl9lWmVJNmt5MlFjY1BPQXdSS3FORWVBYUI2MlBZSHJwNFo0VmtGX2lFaDVRT29RIiwiQXZhaWxhYmxlUHJvZHVjdHMiOiJbXCIxMDA4XCIsXCIxMDUzXCIsXCIxMDA1XCIsXCIxMDExXCIsXCIyMDg5XCIsXCIxMDI2XCIsXCIxMDI3XCIsXCIxMDI4XCIsXCI1MDAwXCIsXCI1MDAxXCIsXCI1MDAzXCIsXCIyMDAwXCIsXCIyMDAxXCIsXCIyMDAyXCIsXCIyMDAzXCIsXCIyMDA0XCIsXCIyMDA1XCJdIiwibmJmIjoxNzI0ODY2NDY5LCJleHAiOjE3MjQ4NzM2NjksImlhdCI6MTcyNDg2NjQ2OSwiaXNzIjoiaHR0cHM6Ly9kdGFwaXVhdC5kYXRhdHJlZS5jb20iLCJhdWQiOiJXZWJBcGlDb25zdW1lcnMifQ.ZEFsMM2kbXSR2fxDob9xWLGOVAl7EVUzW0V3NU53H7c'
            ],
            'body' => json_encode([
                'ProductNames' => ['PropertyDetailReport'],

                "SearchType" => "PROPERTY",
                "PropertyId" => 8948416
            ]),
        ]);*/
        /*$res = $client->request('POST', 'https://dtapiuat.datatree.com/api/Report/GetReport', [
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUTROall4Tmprc0ltNWlaaUk2TVRjeU5EZzJOakUyT1N3aVpYaHdJam94TnpJME9EY3dNRFk1TENKaGFXOGlPaUpCVTFGQk1pODRXRUZCUVVGTFFuQmhhVzVVWjFWeWFHbGhOa05xZDA1ck56RTJWRFkwVkVwR1EyRmhSR2M1U0dkaGIwczVNemc0UFNJc0ltRjZjQ0k2SW1NMllUZzRNbVV4TFRneVl6Y3RORFUwWkMwNU1EVTVMVGRpTVdFNFlqWmpZVEV4TVNJc0ltRjZjR0ZqY2lJNklqRWlMQ0p2YVdRaU9pSmpPR1ZpT0dOaU9DMHlOems0TFRRek9UY3RPREF3WWkwNFpUUTNOalJsTXpKaU1HWWlMQ0p5YUNJNklqQXVRVkV3UVRGc1gwZFVTR0ZqWTFWcGJGRjFjMU53WVdWQlJFZExPRVpVVVV3dFpIUkxhWFJDZGtoc1dsYzRka0ZPUVVGQkxpSXNJbkp2YkdWeklqcGJJa0ZRU1VGalkyVnpjeUpkTENKemRXSWlPaUpqT0dWaU9HTmlPQzB5TnprNExUUXpPVGN0T0RBd1lpMDRaVFEzTmpSbE16SmlNR1lpTENKMGFXUWlPaUkwWTJNMk5XWmtOaTA1WXpjMkxUUTROekV0WVRVME1pMWxZakV5WVRWaE56Z3dNR01pTENKMWRHa2lPaUp4Vm1Wb2JWTlZkVE5yWlVvNFZuZzNRMnB2YWtGQklpd2lkbVZ5SWpvaU1pNHdJaXdpWVhCd1JHRjBZU0k2SW50Y0luVnBaRndpT2pFMU56TTBPU3hjSW1GcFpGd2lPakl3TVRBMU1UUjlJbjAuRlp6UzdqWWljeWt6bHdEelRIVVBCRGg1WG5mNzZCT09Kblp3eE1zTV9nZGZtS1NvOEc0QzJmZElaS21zZ3lCOURLOEF2SDF2OU4yM0JRakJWRGdtVmk0ZkhxOUFrYUZDTEtkU1l6aDJOTE90N3YwajVta0ZCTFg0TXFvSVVvVWFzanc2ZERXTDV6TUtMekhXY2pfbVh0Z0hQN2t5anhUTWxUeDQ1OEVsdmV4WVVOdzliYzZpd1FPZ2ZVcXBaMndxcHVKNllldU9ON0Nsam1oVUJkZmNwem5FaGVudl9NXzNBZFpjUkpfeHhMektwaGIyLUNmMzJlSEE4VmtWZFVpUHpqMTFxZXVvVnBDeWxWUzkwWmFCU3FqNzVqZWRZb2RxN1QzaERvYl9lWmVJNmt5MlFjY1BPQXdSS3FORWVBYUI2MlBZSHJwNFo0VmtGX2lFaDVRT29RIiwiQXZhaWxhYmxlUHJvZHVjdHMiOiJbXCIxMDA4XCIsXCIxMDUzXCIsXCIxMDA1XCIsXCIxMDExXCIsXCIyMDg5XCIsXCIxMDI2XCIsXCIxMDI3XCIsXCIxMDI4XCIsXCI1MDAwXCIsXCI1MDAxXCIsXCI1MDAzXCIsXCIyMDAwXCIsXCIyMDAxXCIsXCIyMDAyXCIsXCIyMDAzXCIsXCIyMDA0XCIsXCIyMDA1XCJdIiwibmJmIjoxNzI0ODY2NDY5LCJleHAiOjE3MjQ4NzM2NjksImlhdCI6MTcyNDg2NjQ2OSwiaXNzIjoiaHR0cHM6Ly9kdGFwaXVhdC5kYXRhdHJlZS5jb20iLCJhdWQiOiJXZWJBcGlDb25zdW1lcnMifQ.ZEFsMM2kbXSR2fxDob9xWLGOVAl7EVUzW0V3NU53H7c'
            ],
            'body' => json_encode([
                'ProductNames' => ['PropertyDetailReport'],

                "SearchType" => "PROPERTY",
                "AddressDetail" => json_encode([
                    "StreetNumber" => "19617",
                    "StreetName" => "Thornlake",
                    "City" => "Cerritos",
                    "StateFips" => 6,
                    "CountyFips" => 6037
                ])
            ]),
        ]);*/
        /*$res = $client->request('POST', 'https://dtapiuat.datatree.com/api/Report/GetReport', [
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUTROall4Tmprc0ltNWlaaUk2TVRjeU5EZzJOakUyT1N3aVpYaHdJam94TnpJME9EY3dNRFk1TENKaGFXOGlPaUpCVTFGQk1pODRXRUZCUVVGTFFuQmhhVzVVWjFWeWFHbGhOa05xZDA1ck56RTJWRFkwVkVwR1EyRmhSR2M1U0dkaGIwczVNemc0UFNJc0ltRjZjQ0k2SW1NMllUZzRNbVV4TFRneVl6Y3RORFUwWkMwNU1EVTVMVGRpTVdFNFlqWmpZVEV4TVNJc0ltRjZjR0ZqY2lJNklqRWlMQ0p2YVdRaU9pSmpPR1ZpT0dOaU9DMHlOems0TFRRek9UY3RPREF3WWkwNFpUUTNOalJsTXpKaU1HWWlMQ0p5YUNJNklqQXVRVkV3UVRGc1gwZFVTR0ZqWTFWcGJGRjFjMU53WVdWQlJFZExPRVpVVVV3dFpIUkxhWFJDZGtoc1dsYzRka0ZPUVVGQkxpSXNJbkp2YkdWeklqcGJJa0ZRU1VGalkyVnpjeUpkTENKemRXSWlPaUpqT0dWaU9HTmlPQzB5TnprNExUUXpPVGN0T0RBd1lpMDRaVFEzTmpSbE16SmlNR1lpTENKMGFXUWlPaUkwWTJNMk5XWmtOaTA1WXpjMkxUUTROekV0WVRVME1pMWxZakV5WVRWaE56Z3dNR01pTENKMWRHa2lPaUp4Vm1Wb2JWTlZkVE5yWlVvNFZuZzNRMnB2YWtGQklpd2lkbVZ5SWpvaU1pNHdJaXdpWVhCd1JHRjBZU0k2SW50Y0luVnBaRndpT2pFMU56TTBPU3hjSW1GcFpGd2lPakl3TVRBMU1UUjlJbjAuRlp6UzdqWWljeWt6bHdEelRIVVBCRGg1WG5mNzZCT09Kblp3eE1zTV9nZGZtS1NvOEc0QzJmZElaS21zZ3lCOURLOEF2SDF2OU4yM0JRakJWRGdtVmk0ZkhxOUFrYUZDTEtkU1l6aDJOTE90N3YwajVta0ZCTFg0TXFvSVVvVWFzanc2ZERXTDV6TUtMekhXY2pfbVh0Z0hQN2t5anhUTWxUeDQ1OEVsdmV4WVVOdzliYzZpd1FPZ2ZVcXBaMndxcHVKNllldU9ON0Nsam1oVUJkZmNwem5FaGVudl9NXzNBZFpjUkpfeHhMektwaGIyLUNmMzJlSEE4VmtWZFVpUHpqMTFxZXVvVnBDeWxWUzkwWmFCU3FqNzVqZWRZb2RxN1QzaERvYl9lWmVJNmt5MlFjY1BPQXdSS3FORWVBYUI2MlBZSHJwNFo0VmtGX2lFaDVRT29RIiwiQXZhaWxhYmxlUHJvZHVjdHMiOiJbXCIxMDA4XCIsXCIxMDUzXCIsXCIxMDA1XCIsXCIxMDExXCIsXCIyMDg5XCIsXCIxMDI2XCIsXCIxMDI3XCIsXCIxMDI4XCIsXCI1MDAwXCIsXCI1MDAxXCIsXCI1MDAzXCIsXCIyMDAwXCIsXCIyMDAxXCIsXCIyMDAyXCIsXCIyMDAzXCIsXCIyMDA0XCIsXCIyMDA1XCJdIiwibmJmIjoxNzI0ODY2NDY5LCJleHAiOjE3MjQ4NzM2NjksImlhdCI6MTcyNDg2NjQ2OSwiaXNzIjoiaHR0cHM6Ly9kdGFwaXVhdC5kYXRhdHJlZS5jb20iLCJhdWQiOiJXZWJBcGlDb25zdW1lcnMifQ.ZEFsMM2kbXSR2fxDob9xWLGOVAl7EVUzW0V3NU53H7c'
            ],
            'body' => json_encode([
                'ProductNames' => ['SalesComparables'],

                "SearchType" => "PROPERTY",
                "AddressDetail" => json_encode([
                    "StreetNumber" => "19617",
                    "StreetName" => "Thornlake",
                    "City" => "Cerritos",
                    "StateFips" => 6,
                    "CountyFips" => 6037
                ]),
                "SalesCompSettings" => json_encode([
                    "CompsMaxNumber" => 25
                ]),
            ]),
        ]);*/
        $d1 = 5;
        $d2 = 15;
        $res = $client->request('POST', 'https://dtapiuat.datatree.com/api/Report/GetReport', [
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUTROekF4TWpRc0ltNWlaaUk2TVRjeU5EZzNNREV5TkN3aVpYaHdJam94TnpJME9EYzBNREkwTENKaGFXOGlPaUpCVTFGQk1pODRXRUZCUVVGTU5rODFLMFZvY204dlkweGtPR1V5Ymk4MmJqRjBZVVZoUW05U04xZHhiRE01UldKSFpYZHVXWEZCUFNJc0ltRjZjQ0k2SW1NMllUZzRNbVV4TFRneVl6Y3RORFUwWkMwNU1EVTVMVGRpTVdFNFlqWmpZVEV4TVNJc0ltRjZjR0ZqY2lJNklqRWlMQ0p2YVdRaU9pSmpPR1ZpT0dOaU9DMHlOems0TFRRek9UY3RPREF3WWkwNFpUUTNOalJsTXpKaU1HWWlMQ0p5YUNJNklqQXVRVkV3UVRGc1gwZFVTR0ZqWTFWcGJGRjFjMU53WVdWQlJFZExPRVpVVVV3dFpIUkxhWFJDZGtoc1dsYzRka0ZPUVVGQkxpSXNJbkp2YkdWeklqcGJJa0ZRU1VGalkyVnpjeUpkTENKemRXSWlPaUpqT0dWaU9HTmlPQzB5TnprNExUUXpPVGN0T0RBd1lpMDRaVFEzTmpSbE16SmlNR1lpTENKMGFXUWlPaUkwWTJNMk5XWmtOaTA1WXpjMkxUUTROekV0WVRVME1pMWxZakV5WVRWaE56Z3dNR01pTENKMWRHa2lPaUl6ZUcxbFJWQXlVMGN3UzNZNWJqYzRZbmt3Y0VGQklpd2lkbVZ5SWpvaU1pNHdJaXdpWVhCd1JHRjBZU0k2SW50Y0luVnBaRndpT2pFMU56TTBPU3hjSW1GcFpGd2lPakl3TVRBMU1UUjlJbjAueUx3OUdyX0JCeWM1bmwyUVF0STJHMTFBcS15TWhpejFmRm9GVC10QkowZ01hVVNFbjFxMXJJMUlWTGlBcGlYX1ZpT2l2N2dySTNSOUxZZTBxZ3lvU0RpUmkxanB0NVZIaDRHVWU3VFZTLTRQVEVLazk0S1BteVl0SHV0Zy1TU3pwUFNSMWxTb2NrT3ZtOVRBM3l4UGhoWFlweC1ScUdEVFFaY2FmNGtTT2QzWXdDQ1RNdlp6S0hMTlJSaGxrWVc4VjJKLXMtMHQwOXVnd1UzQjhmVkJ5c1JvNGM5STREUkFFeHFHNUdISVFrM2hkQ05nQWFxUHoxbHFiTVh6YlA5bGhsNXYyMExRNnY0bEFLOWcyQ0dMQUNDWU4zNzRyY1pGWlFGSk81aGdMSWRkTDZXUUlYVmZhV1JQTEpfMEdodGY3Ym1OTmF3c0pBMXpUOUluOWxvNVlRIiwiQXZhaWxhYmxlUHJvZHVjdHMiOiJbXCIxMDA4XCIsXCIxMDUzXCIsXCIxMDA1XCIsXCIxMDExXCIsXCIyMDg5XCIsXCIxMDI2XCIsXCIxMDI3XCIsXCIxMDI4XCIsXCI1MDAwXCIsXCI1MDAxXCIsXCI1MDAzXCIsXCIyMDAwXCIsXCIyMDAxXCIsXCIyMDAyXCIsXCIyMDAzXCIsXCIyMDA0XCIsXCIyMDA1XCJdIiwibmJmIjoxNzI0ODcwNDI0LCJleHAiOjE3MjQ4Nzc2MjQsImlhdCI6MTcyNDg3MDQyNCwiaXNzIjoiaHR0cHM6Ly9kdGFwaXVhdC5kYXRhdHJlZS5jb20iLCJhdWQiOiJXZWJBcGlDb25zdW1lcnMifQ.yjuh05dP8Rpto9uPu5CrHf4Gps28lHKvwH-wvz-GBVY'
            ],
            'body' => '{
  "ProductNames": [
    "SalesComparables"
  ],
  "SearchType": "Filter",
  "SalesCompSettings": {
    "CompsMaxNumber": 25
  },
  "SearchRequest": {
    "ReferenceId": "1",
    "ProductName": "SearchLite",
    "MaxReturn": "1",
    "Filters": [
      {
        "FilterName": "LotAcreage",
        "FilterOperator": "is between",
        "FilterValues": [
          '.$d1.',
          '.$d2.'
        ]
      }
    ]
  }
}',
        ]);
        /*"AddressDetail": {
    "StreetNumber": "19617",
    "StreetName": "Thornlake",
    "City": "Cerritos",
    "ZipCode": "90703",
    "StateFips": 6,
    "CountyFips": 6037
  }*/
        //dd($res->getBody());
        //token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUTROakl4TXpRc0ltNWlaaUk2TVRjeU5EZzJNakV6TkN3aVpYaHdJam94TnpJME9EWTJNRE0wTENKaGFXOGlPaUpGTW1SbldVWkJkbGhqWVRsaFdYQndVV1pyU0M5dk1UVlJWRXRMYm1Kek1HWkdOM2hwVEhaak4ycHNhREJDZVRSbVFrbEJJaXdpWVhwd0lqb2lZelpoT0RneVpURXRPREpqTnkwME5UUmtMVGt3TlRrdE4ySXhZVGhpTm1OaE1URXhJaXdpWVhwd1lXTnlJam9pTVNJc0ltOXBaQ0k2SW1NNFpXSTRZMkk0TFRJM09UZ3RORE01TnkwNE1EQmlMVGhsTkRjMk5HVXpNbUl3WmlJc0luSm9Jam9pTUM1QlVUQkJNV3hmUjFSSVlXTmpWV2xzVVhWelUzQmhaVUZFUjBzNFJsUlJUQzFrZEV0cGRFSjJTR3hhVnpoMlFVNUJRVUV1SWl3aWNtOXNaWE1pT2xzaVFWQkpRV05qWlhOeklsMHNJbk4xWWlJNkltTTRaV0k0WTJJNExUSTNPVGd0TkRNNU55MDRNREJpTFRobE5EYzJOR1V6TW1Jd1ppSXNJblJwWkNJNklqUmpZelkxWm1RMkxUbGpOell0TkRnM01TMWhOVFF5TFdWaU1USmhOV0UzT0RBd1l5SXNJblYwYVNJNkltTlNkV0pPTVRoSGNWVjVVMFprTUdOa2FVRkJRVkVpTENKMlpYSWlPaUl5TGpBaUxDSmhjSEJFWVhSaElqb2llMXdpZFdsa1hDSTZNVFUzTXpRNUxGd2lZV2xrWENJNk1qQXhNRFV4TkgwaWZRLlVnN2lVSkIyVkZJbEVWWEkyWlRjNnNCUnVJVE5zWUtRMmI5NmtBODI3Z2hoVG85ck43aXNoQ3I5aDRGNktkREphOFAwWWx6RHYwbDVxQWlDM1Rvd1czUlpIdUxBdWdObEVGR0JXaWEtUDdBMnlhc1lwRTdQb1d4ZUNiYVc5LTBPOEsyLTdGOU1IM01QNVd2YkZJN0JBeWF0bmhrdXFWT0tMcF9YakpVc0x5aGV3bXo4Nk4wOHhIZEc4LXdubUg5TG5MMERDTlZRODZJcFFIckhCN0ZaS0lHWmtHd3dKa1E2WkYtVXFRT0VKSG1RX01sRkR2Y2JTV1FEcjNtUHdCMXdfWVkzTzZ4ODlBOXc4R2ZuMEJ2MUx4aWZJNHVYM1E1dTdPYmRIZExjYk5wWGdmYW9ZYmp6Q2c1VHYxNURSZ1BtUzJPNUdoU0tGb2o3WnFSay1ueExFUSIsIkF2YWlsYWJsZVByb2R1Y3RzIjoiW1wiMTAwOFwiLFwiMTA1M1wiLFwiMTAwNVwiLFwiMTAxMVwiLFwiMjA4OVwiLFwiMTAyNlwiLFwiMTAyN1wiLFwiMTAyOFwiLFwiNTAwMFwiLFwiNTAwMVwiLFwiNTAwM1wiLFwiMjAwMFwiLFwiMjAwMVwiLFwiMjAwMlwiLFwiMjAwM1wiLFwiMjAwNFwiLFwiMjAwNVwiXSIsIm5iZiI6MTcyNDg2MjQzNCwiZXhwIjoxNzI0ODY5NjM0LCJpYXQiOjE3MjQ4NjI0MzQsImlzcyI6Imh0dHBzOi8vZHRhcGl1YXQuZGF0YXRyZWUuY29tIiwiYXVkIjoiV2ViQXBpQ29uc3VtZXJzIn0.HEk-0bBPwQkJW-oMvm_9reifemWY1-NiN-sTSAZc7r0'

        //echo $res->getStatusCode();
        // "200"
        //echo $res->getHeader('content-type')[0];
        // 'application/json; charset=utf8'
        $users = json_decode($res->getBody(), true);
        dd($users);
        /*$response = Http::withHeaders([
            'Accept' => 'application/json',
            'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUTROVFkzTmpZc0ltNWlaaUk2TVRjeU5EZzFOamMyTml3aVpYaHdJam94TnpJME9EWXdOalkyTENKaGFXOGlPaUpCVTFGQk1pODRXRUZCUVVFek5WcFJMekl4TmpKSGMwWkRiSGRSUlhKaU5tNDJUR2xuV2tWaGIyaEdMMng1U1ROQ09XZGlNV0ZyUFNJc0ltRjZjQ0k2SW1NMllUZzRNbVV4TFRneVl6Y3RORFUwWkMwNU1EVTVMVGRpTVdFNFlqWmpZVEV4TVNJc0ltRjZjR0ZqY2lJNklqRWlMQ0p2YVdRaU9pSmpPR1ZpT0dOaU9DMHlOems0TFRRek9UY3RPREF3WWkwNFpUUTNOalJsTXpKaU1HWWlMQ0p5YUNJNklqQXVRVkV3UVRGc1gwZFVTR0ZqWTFWcGJGRjFjMU53WVdWQlJFZExPRVpVVVV3dFpIUkxhWFJDZGtoc1dsYzRka0ZPUVVGQkxpSXNJbkp2YkdWeklqcGJJa0ZRU1VGalkyVnpjeUpkTENKemRXSWlPaUpqT0dWaU9HTmlPQzB5TnprNExUUXpPVGN0T0RBd1lpMDRaVFEzTmpSbE16SmlNR1lpTENKMGFXUWlPaUkwWTJNMk5XWmtOaTA1WXpjMkxUUTROekV0WVRVME1pMWxZakV5WVRWaE56Z3dNR01pTENKMWRHa2lPaUpGWVVZMmRTMUNWVzVWVDJKVWRuWjNkQzFqUzBGUklpd2lkbVZ5SWpvaU1pNHdJaXdpWVhCd1JHRjBZU0k2SW50Y0luVnBaRndpT2pFMU56TTBPU3hjSW1GcFpGd2lPakl3TVRBMU1UUjlJbjAuUi1WMWFleTlmVDNTNGZ4d0U3Um5nRUh4SkFleE01TjVLWDFjVVVIckgwUzU1UnlXVmFWQ0t6Y2FNclE2eU1mdGVyRWhpLUwtYkQ0VGFFelJvNTdlME44ZVoyOEY0aFJxUzlaMEVTbmNhYmlVcmhNeVBrc3VnOWhfYV9Gby01WVR1enAzc1JJX3lsdkl5Sm5yNF9RNllKTTB1WlhaQi15VGlkeWthbGVfLXVKZDVjejZ2eUxsMUZURGU0dF81dzFoYnl5WS1mNlNSNEQ5bURjejdKOHQ4ZUsyaGFUeHJjNzBnWGFDSnBMckhkbTF1d3ZxbFM1UU00aGxNWGhGS0pUMWExM2t0WDNLaVRhS2tudDl3MVRuRTMxU0NFNjhyRHE1RkJDRk40enFzTzZWOG9Bd255eS1Wb29BX1Bqc3NWbkZxV25KZkp6UDlRXzlkZDc2WWtmeEdRIiwiQXZhaWxhYmxlUHJvZHVjdHMiOiJbXCIxMDA4XCIsXCIxMDUzXCIsXCIxMDA1XCIsXCIxMDExXCIsXCIyMDg5XCIsXCIxMDI2XCIsXCIxMDI3XCIsXCIxMDI4XCIsXCI1MDAwXCIsXCI1MDAxXCIsXCI1MDAzXCIsXCIyMDAwXCIsXCIyMDAxXCIsXCIyMDAyXCIsXCIyMDAzXCIsXCIyMDA0XCIsXCIyMDA1XCJdIiwibmJmIjoxNzI0ODU3MDY2LCJleHAiOjE3MjQ4NjQyNjYsImlhdCI6MTcyNDg1NzA2NiwiaXNzIjoiaHR0cHM6Ly9kdGFwaXVhdC5kYXRhdHJlZS5jb20iLCJhdWQiOiJXZWJBcGlDb25zdW1lcnMifQ.X3tEkG3VQ0XLdYfawp9seCZUheUkzYnxtj0DG0hRAmc'
        ])->post('https://dtapiuat.datatree.com/api/Report/GetReport?Ver=1.0', [
            'name' => 'Steve',
            'role' => 'Network Administrator',
        ]);*/
        //return view('test');
        //dd($id);
        /*$client = new Client();
        //dd($client);
        $url = "https://dtapiuat.datatree.com/api/Report/GetReport";
        $token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxNTczNDkiLCJBY2NvdW50SUQiOiIyMDEwNTE0IiwiVXNlck5hbWUiOiJEVEFQSV9wcm9wZWx5emVfVUFUIiwiTmFtZSI6IkZhcmhhbiBCYWtodCIsIlVzZXJFbWFpbCI6InByb3BlbHl6ZUBnbWFpbC5jb20iLCJJU1JlZmVyZW5jZVJlcXVpcmVkIjoiMCIsIkFjY291bnRUeXBlIjoiMCIsIk9BdXRoVG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdFJNblJCWTNKRk4yeENZVlpXUjBKdFl6VkdiMkpuWkVwdk5DSjkuZXlKaGRXUWlPaUl6TkRFMVltTTJNaTFtT1RCaUxUUmhaR0l0T0dGa01DMDJaakZsTlRZMU5tWXlaakFpTENKcGMzTWlPaUpvZEhSd2N6b3ZMMnh2WjJsdUxtMXBZM0p2YzI5bWRHOXViR2x1WlM1amIyMHZOR05qTmpWbVpEWXRPV00zTmkwME9EY3hMV0UxTkRJdFpXSXhNbUUxWVRjNE1EQmpMM1l5TGpBaUxDSnBZWFFpT2pFM01qUTROVFV5TURRc0ltNWlaaUk2TVRjeU5EZzFOVEl3TkN3aVpYaHdJam94TnpJME9EVTVNVEEwTENKaGFXOGlPaUpGTW1SbldVUkVjMDlRUkUxd2RtbDFlRXB3WlRWWVpDOTJia1ZWY2xGc05Va3pRbTlvTjNRM2NHUjRURk5SZEhJMWFrRkJJaXdpWVhwd0lqb2lZelpoT0RneVpURXRPREpqTnkwME5UUmtMVGt3TlRrdE4ySXhZVGhpTm1OaE1URXhJaXdpWVhwd1lXTnlJam9pTVNJc0ltOXBaQ0k2SW1NNFpXSTRZMkk0TFRJM09UZ3RORE01TnkwNE1EQmlMVGhsTkRjMk5HVXpNbUl3WmlJc0luSm9Jam9pTUM1QlVUQkJNV3hmUjFSSVlXTmpWV2xzVVhWelUzQmhaVUZFUjBzNFJsUlJUQzFrZEV0cGRFSjJTR3hhVnpoMlFVNUJRVUV1SWl3aWNtOXNaWE1pT2xzaVFWQkpRV05qWlhOeklsMHNJbk4xWWlJNkltTTRaV0k0WTJJNExUSTNPVGd0TkRNNU55MDRNREJpTFRobE5EYzJOR1V6TW1Jd1ppSXNJblJwWkNJNklqUmpZelkxWm1RMkxUbGpOell0TkRnM01TMWhOVFF5TFdWaU1USmhOV0UzT0RBd1l5SXNJblYwYVNJNklrcEZlVlJqYkRsc1pXdGxVVFZ5UVVsMWMxaEhRVUVpTENKMlpYSWlPaUl5TGpBaUxDSmhjSEJFWVhSaElqb2llMXdpZFdsa1hDSTZNVFUzTXpRNUxGd2lZV2xrWENJNk1qQXhNRFV4TkgwaWZRLkdyU1g2VHZldlRYeFE0eFpuSTlpcEpxRUdORGI5TkNXamppN2FUXzEtLVRNeEN0dU9RdU1wNlZlalhPWk5tNjA3d3czS2Z3dXJKck1KQ3Q5ZWdEM1h2d1RMbFo2THlZMm5PNldjaW80Q1JzMTdQSWV1Wm95Rm1jZUpkOUhBdzg1RjB2bzJxZ2xSYkp1SndnaTZuWlF6U0RKR2ZodS0ycExRdGozWWpUUWFIdG83c0J4aG00MHowblNaRXRySjJBbE1OWTRzemVhTjBFbEhiaExiYko3ZV9ZZjJ5X2ktNjlOVEs5a1YxRnRUTUE0TEhrQ0xES2dGVlZVNTVfY1NTMzlwaXlORjM0VHYwTS05WmRXeExhVGRvYVN5WF92V3RkLUF6WlFaWDc0S3QtcThyXzdOZ1ppZUNQNXZPVXlOd0czVE5GcTUtT2M3N2c0Q3NieEZXc3BXQSIsIkF2YWlsYWJsZVByb2R1Y3RzIjoiW1wiMTAwOFwiLFwiMTA1M1wiLFwiMTAwNVwiLFwiMTAxMVwiLFwiMjA4OVwiLFwiMTAyNlwiLFwiMTAyN1wiLFwiMTAyOFwiLFwiNTAwMFwiLFwiNTAwMVwiLFwiNTAwM1wiLFwiMjAwMFwiLFwiMjAwMVwiLFwiMjAwMlwiLFwiMjAwM1wiLFwiMjAwNFwiLFwiMjAwNVwiXSIsIm5iZiI6MTcyNDg1NTUwNCwiZXhwIjoxNzI0ODYyNzA0LCJpYXQiOjE3MjQ4NTU1MDQsImlzcyI6Imh0dHBzOi8vZHRhcGl1YXQuZGF0YXRyZWUuY29tIiwiYXVkIjoiV2ViQXBpQ29uc3VtZXJzIn0.L6yQsSaMfI1P8XYk9eydJ8aieWACH9LhflETw5-2vPE';

        $request = $client->post($url, [
            'headers' => [
                'Authorization' => 'Bearer '.$token
            ],
            'body' => json_encode([
                'PropertyId' => '8948416',
            ])

        ]);
        //dd($request);

        $response = json_decode($request->getBody());
        dd($response);
        //$token = $response->result->token;
        if (!empty($id)) {
            $data = [
                'title' => 'abc',
                'content' => 'Lorem ipsum',
                'logo' => public_path('img/logo.png'),
                'image' => public_path('img/th.jpg'),
            ];
            $pdf = Pdf::loadView('pdf', $data);
            //return $pdf->download('compreport.pdf');
            return response()->json([
                'status' => true,
                'success' => true,
                'message' => 'some thing wrong',
            ]);
        } else {
            return response()->json([
                'status' => false,
                'success' => false,
                'message' => 'some thing wrong',
            ]);
        }*/
    }
}
